# syntax=docker/dockerfile:1

FROM python:3.12.7-bookworm

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080
CMD ["gunicorn", "-w", "4", "--worker-class", "gevent", "--timeout", "0", "web:create_app()"]